image: maven:3-adoptopenjdk-14

junit:
  stage: test
  script:
    - mvn test

pages:
  stage: deploy
  script:
    - mvn javadoc:javadoc
    - mkdir .public
    - cp -r target/site .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
